### ISSUE TITLE
Deploy Full Stack App to Heroku

### ISSUE THREAD

**Issue by JasonToups** [JasonToups/zeal-recipies#1]
## Goal
Use the Heroku Documentation to deploy the App to Heroku.

### Links
Heroku Documentation [Prepare a Codebase for Heroku Deployment](https://devcenter.heroku.com/articles/preparing-a-codebase-for-heroku-deployment)

## ToDos
- [ ] Create GitHub Repository
- [ ] Install Heroku CLI
- [ ] Create Heroku App
- [ ] Setup files to deploy
- [ ] Deploy app to Heroku
- [ ] Test app on Heroku
- [ ] Write any documentation to deploy in the `README.md`
